// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package fi.fullerine.kingofthestreets.domain.commutereval;

import fi.fullerine.kingofthestreets.domain.commutereval.EvaluationIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EvaluationIntegrationTest_Roo_Configurable {
    
    declare @type: EvaluationIntegrationTest: @Configurable;
    
}
